function creapentastella(n,xxc,yyc,rr,stringa)
% function creapentastella(n,xxc,yyc,rr,stringa)
% inputs
%        n -  number of times in which the five-pointed star curve will 
%             be replicated along the band
%        xcc - x-coordinates of the centroids of the  curve 
%        ycc - y-coordinates of the centroids of the  curve
%        rr - radius of the circles containing the curve.
%        stringa - The color of the lines and curves generated by the function.
% output
%      This function has no output variable; it just generates the plot.
%
% MIT license 
% Copyright (c) Annamaria Mazzia
%
% Load coordinates for the five-points star curve. The points are generated by
% the script_fivepointstarcurve.m script
datid=load('pentastella.dat');
dx1=datid(1,:);
dy1=datid(2,:);
theta1=linspace(pi/2,pi/2+2*pi,n+1);
theta=linspace(0,2*pi);
rot=@(t1) [cos(t1) -sin(t1); sin(t1) cos(t1)]; % rotation matrix function
for j=1:n
    dxx=rr*dx1; dyy=rr*dy1; %dilation
    for i=1:length(dx1)
        y=rot(theta1(j)-pi/2)*[dxx(i); dyy(i)]; %rotation
        dxx(i)=y(1)+xxc(j); % translation
        dyy(i)=y(2)+yyc(j);
    end
    % plot of the five-points star curve
    plot(dxx,dyy,'Color',stringa,'LineWidth',2,'LineJoin', 'chamfer')
    %plot of the circle containg the curve
    x=xxc(j)+rr*cos(theta);
    y=yyc(j)+rr*sin(theta);
    plot(x,y,'Color',stringa,'LineWidth',2,'LineJoin', 'chamfer')
end


end