function fourcircles(r0,stringa)
% function  r=fourcircles(r0,stringa)
% inputs
%      r0 - inner radius of the circular band
%      stringa - The color of  curves generated by the function.
% output
%        This function has no output variable; it just generates the plot.
% MIT license 
% Copyright (c) Annamaria Mazzia
%
theta=linspace(0,2*pi);
n=4;
theta0=linspace(0,2*pi,n+1);
xx0=2*r0*cos(theta0(1:n)); yy0=2*r0*sin(theta0(1:n)); % coordinates of the 
% centroids of the small circles
% contruction of the small four circles with radius equal to r0
for i=1:n
    x=xx0(i)+r0*cos(theta);
    y=yy0(i)+r0*sin(theta);
    plot(x,y,'color',stringa,'LineWidth',2, 'LineJoin', 'chamfer')
    hold on
end
axis square
r1=5*r0;
theta1=linspace(pi/4,pi/4+2*pi,n+1);
xu=r1*cos(theta1(1:n)); yu=r1*sin(theta1(1:n)); % coordinates of the 
% centroids of the large circles
%
% Construction of the four large portions of circles with radius r1.
% Each arc starts where it meets a small circle and ends where it meets 
% the next large circle
for i=1:n 
     theta2=linspace(theta1(i)-pi/2, theta1(i)+pi-pi/8);
     xi=xu(i)+r1*cos(theta2);
     yi=yu(i)+r1*sin(theta2);
     plot(xi,yi,'color',stringa,'LineWidth',2,'LineJoin', 'chamfer')
 end
end