function  r0=funleaves(n,r,choice,stringa)
%function  ru=funleaves(n,r,stringa)
% inputs
%      n -  number of times in which the parametric curve will be replicated
%           along the band
%      r -  the radius of the circles within which we place the parametric curves
%      choice -  variable to select the type of decoration used to create the lily flower.
%      stringa - The color of the lines and curves generated by the function.
% output
%       r0 - The outer radius of the band.
% MIT license 
% Copyright (c) Annamaria Mazzia
%
p=5; % factor to plot n columns along the band and draw left and right
     % tangent circles.
m=p*n; 
rold=r;
r=rold+1;
theta=linspace(0,2*pi); % vector used to draw the circles
theta1=linspace(pi/2,pi/2+2*pi,m+1); %vector used to draw the columns
xx=r*cos(theta1(1:m)); yy=r*sin(theta1(1:m)); % Centroids of the curves
% that will be placed to the left and right of the columns (stems).
rr=norm([xx(1), yy(1)]-[xx(2),yy(2)]);
r0=r+rr*0.8; % outer radius for the band 
r00=rold;  % internal radius for the band
xx0=r0*cos(theta1(1:p:m)); yy0=r0*sin(theta1(1:p:m)); % points at the top
% of the columns (stems)
xx00=r00*cos(theta1(1:p:m)); yy00=r00*sin(theta1(1:p:m)); % points at the
% base of the columns (stems)
for j=1:n
plot([xx0(j) xx00(j)],[yy0(j) yy00(j)], 'Color',stringa,'LineWidth',4,'LineJoin', 'chamfer')
end
rot=@(t1) [cos(t1) -sin(t1); sin(t1) cos(t1)]; % Rotation matrix function
switch choice
    case 1
[sxx, syy]=circle(rr*0.8,theta); % Circle that will be rotated around the 
% band 
    case 2
        % Archimedean spiral
sxx=rr*0.15*theta.*cos(theta);
syy=-rr*0.15*theta.*sin(theta);
end
% Preallocate variables for the left and right circles tangent to each column.
sxxl=zeros(size(sxx));
syyl=zeros(size(sxx));
sxxr=zeros(size(sxx));
syyr=zeros(size(sxx));
% rotation and translation of the circles
for j=1:p:m
    k=j+1;
    for i=1:length(sxx)
      aux=rot(theta1(k)-pi/2)*[sxx(i); syy(i)];
      sxxl(i)=aux(1)+xx(k);
      syyl(i)=aux(2)+ yy(k);
    end
    plot(sxxl,syyl,'Color',stringa,'LineWidth',3,'LineJoin', 'chamfer')
    k=k+p-2;
    for i=1:length(sxx)
        switch choice
              case 1
                aux=rot(theta1(k)-pi/2)*[sxx(i); syy(i)];
            case 2
               aux=rot(theta1(k)-pi/2)*[-sxx(i); syy(i)];
        end
      sxxr(i)=aux(1)+xx(k);
      syyr(i)=aux(2)+yy(k);
    end
    plot(sxxr,syyr,'Color',stringa,'LineWidth',3,'LineJoin', 'chamfer')
end
%

 
end
