function  funlily(n,r,stringa)
%function  funlily(n,r,stringa)
% inputs
%           n -  Number of times in which the lily decoration will be replicated
%                along the band
%           r - The radius of the circles where the lily petals begin.
%           stringa - The color of the lines and curves generated by the function.
% output
%         This function has no output variable; it just generates the plot.
%      
% MIT license 
% Copyright (c) Annamaria Mazzia
%
% Load coordinates for the left (gigliol.txt) and right (gigliod.txt) 
% lily petals. The coordinates were generated by a Bézier algorithm (see
% script_makelily.m)
datid=load('gigliod.txt'); % x and y -coordinates of the right petal.
datil=load('gigliol.txt'); % x and y -coordinates of the left petal.
%
dx1=datid(:,1); % x-coordinates of the right petal.
dy1=datid(:,2); % y-coordinates of the right petal.
sx1=datil(:,1); % x-coordinates od the left petal.
sy1=datil(:,2); % y-coordinates of the left petal.
theta1=linspace(pi/2,pi/2+2*pi,n+1);
xxc=r*cos(theta1(1:n)); yyc=r*sin(theta1(1:n)); % The coordinates of the 
% centroid points that are the centers from which the petals start.
rr=norm([xxc(1), yyc(1)]-[xxc(2),yyc(2)])*0.8; % The radius of the circles 
%  containing the lily petals.
rot=@(t1) [cos(t1) -sin(t1); sin(t1) cos(t1)]; % rotation matrix function
for j=1:n
 % dilation
 dxx=rr*dx1; dyy=rr*dy1;
 sxx=rr*sx1; syy=rr*sy1;
for i=1:length(sx1)
    % left petal
    aux=rot(theta1(j)-pi/2)*[sxx(i); syy(i)];  % rotation
    sxx(i)=aux(1)+xxc(j); % translation
    syy(i)=aux(2)+yyc(j);
    % right petal
    aux=rot(theta1(j)-pi/2)*[dxx(i); dyy(i)]; % rotation
    dxx(i)=aux(1)+xxc(j); % translation
    dyy(i)=aux(2)+yyc(j);
end
plot(sxx,syy,'Color',stringa,'LineWidth',2,'LineJoin', 'chamfer')
plot(dxx,dyy,'Color',stringa,'LineWidth',2,'LineJoin', 'chamfer')

end
 
end
