function  funleavesribbon(n,r,stringa)
%function  funleavesribbon(n,r,stringa)
% inputs
%      n -  number of times in which the ribbon-like curve will be replicated
%           along the band
%      r -  the radius of the circles within which we place the parametric curves
%      stringa - The color of the lines and curves generated by the function.
% output
%      This function has no output variable; it just generates the plot.
% MIT license 
% Copyright (c) Annamaria Mazzia
%
% Load coordinates for the ribbon-like curve.
%The coordinates were generated by loading an image of the rose window 
% of the San Rufino church. We then used the ginput function to select a 
% specific number of points and, finally, interpolated with a spline to 
% obtain the points for the ribbon-like curve.
dati1=load('ribbondata.txt');
sx1=dati1(1,:);
sy1=dati1(2,:);
m=2*n; 
theta1=linspace(pi/2,pi/2+2*pi,m+1);
xxc=r*cos(theta1(2:2:m+1)); yyc=r*sin(theta1(2:2:m+1)); % The coordinates 
% of the centroid points that are the centers from which the curve start.
rr=norm([xxc(1), yyc(1)]-[xxc(2),yyc(2)])/2; % The radius of the circles 
%  containing the curves.
r0=r+rr; % outer radius for the band 
r00=r-rr; % internal radius for the band
xx0=r0*cos(theta1(1:2:m)); yy0=r0*sin(theta1(1:2:m)); % points at the top
% of the stems
xx00=r00*cos(theta1(1:2:m)); yy00=r00*sin(theta1(1:2:m)); % points at the
% base of the stems
jj=2;
rot=@(t1) [cos(t1) -sin(t1); sin(t1) cos(t1)]; % rotation matrix function
for j=1:n
    sxx=rr*sx1; syy=rr*sy1; %dilation 
    for i=1:length(sx1)
        y=rot(theta1(jj)-pi/2)*[sxx(i); syy(i)]; %rotation 
        sxx(i)=y(1)+xxc(j); %translation 
        syy(i)=y(2)+yyc(j);
    end
    jj=jj+2;
    plot(sxx,syy,'Color',stringa,'LineWidth',2,'LineJoin', 'chamfer')
    hold on
    plot([xx0(j) xx00(j)],[yy0(j) yy00(j)], 'Color',stringa,'LineWidth',2,'LineJoin', 'chamfer')
end
 
end
