function rc1=funlilydecor(n,r0,r,stringa)
% function rc1=funlilydecor(n,r0,r,stringa)
% inputs
%        n - Number of times in which the parametric curve will be replicated
%            along the band
%        r0 - Starting radius for the lily decorations, measured from the columns.
%        r  - The radius of the circles where the lily petals begin.
%        stringa - The color of the lines and curves generated by the function.
% output
%       rc1 - The distance between two lily decorations.
%
% MIT license 
% Copyright (c) Annamaria Mazzia
%
theta1=linspace(pi/2,pi/2+2*pi,n+1);
xx0=r0*cos(theta1(1:n)); yy0=r0*sin(theta1(1:n)); % The coordinates of the
% base stem for the lily decorations
xx=r*cos(theta1(1:n)); yy=r*sin(theta1(1:n));  % The coordinates of the centroid 
% points that serve as the center for the lily petals.
rc1=norm([xx(1) yy(1)]-[xx(2) yy(2)])/2; % the radius of the circles where
% we place the lily decorations
%
% Coordinates of the endpoints for the lily stems.
 xxn=(r+1.3*rc1)*cos(theta1(1:n)); yyn=(r+1.3*rc1)*sin(theta1(1:n));  
% plot of the stems
for i=1:n
plot([xx0(i) xxn(i)],[yy0(i) yyn(i)],'Color',stringa,'LineWidth',4,'LineJoin', 'chamfer') 
end
% The plot of the lily decorations around the band
funlily(n,r,stringa)
end
