function  rc1=funreplicateflower(n,r,xxf,yyf,stringa)
%function  rc1=funreplicateflower(n,r,xxf,yyf,stringa)
% inputs
%      n -  number of times in which the parametric curve will be replicated
%           along the band
%      r -  the radius of the circles within which we place the parametric curves
%      xxf - x-coordinates of the parametric curve
%      yyf - y-coordinates of the parametric curve
%      stringa - The color of the lines and curves generated by the function.
% output
%        rc1 - The radius of the arches.
% MIT license 
% Copyright (c) Annamaria Mazzia
%
theta1=linspace(pi/2,pi/2+2*pi,n+1);
xx=r*cos(theta1(1:n)); yy=r*sin(theta1(1:n));  % The coordinates of the centroid 
%points that serve as the center for the parametric curve's rotation 
%around the band
rc1=norm([xx(1) yy(1)]-[xx(2) yy(2)])/2; % the radius of the circles where
% we place the parametrice curves.
dilfact=max(abs([xxf,yyf]));  % dilation factor to have the initial shape in the
%  unit circle.
xxf=xxf/dilfact; yyf=yyf/dilfact; % the new points to be translated and rotated.
% rotation matrix function
rot=@(t1) [cos(t1) -sin(t1); sin(t1) cos(t1)];
% loop to make dilation, rotation and translation of the parametric curve
for j=1:n
 dxx=rc1*xxf; dyy=rc1*yyf;  % dilation
for i=1:length(dxx)
    y=rot(theta1(j)-pi/2)*[dxx(i); dyy(i)]; % rotation
    dxx(i)=y(1)+xx(j);  % translation
    dyy(i)=y(2)+yy(j);
end
plot(dxx,dyy,'Color',stringa,'LineWidth',2,'LineJoin', 'chamfer')
end
%
end
