function [ xxc,yyc, rc1,theta1]=ncrosspetals(n,r0,r,stringa)
% function [ xxc,yyc, rc1,theta1]=ncrosspetals(n,r0,r,stringa)
% inputs
%        n -  The number of columns  with their arches.
%        r0 - The starting radius of the columns.
%        r  - The ending radius of the columns.
%        stringa - The color of the lines and curves generated by the function.
% output
%        xcc - x-coordinates of the centroids of the arches
%        ycc - y-coordinates of the centroids of the arches
%        rc1 - The radius of the arches.
%        theta1 - angles that separate the centroids of the arches
%
% MIT license 
% Copyright (c) Annamaria Mazzia
%
theta1=linspace(pi/2,pi/2+2*pi,2*n+1);
% construction of the columns
m=2*n;
xx0=r0*cos(theta1(1:2:m)); yy0=r0*sin(theta1(1:2:m)); % segment base vertices
xx=r*cos(theta1(1:2:m)); yy=r*sin(theta1(1:2:m));  % segment end vertices
for i=1:n
    plot([xx0(i) xx(i)],[yy0(i) yy(i)],'Color',stringa,'LineWidth',3,'LineJoin', 'chamfer')
end
%
xxc=zeros(1,n); yyc=zeros(1,n);
% % construction of the  arches' centroids
for i=1:n
    if i==1; jprev=n; else; jprev=i-1; end
    if i==n; jnext=1; else; jnext=i+1; end
    xxc(i)=(xx(jprev)+xx(jnext))/2;
    yyc(i)=(yy(jprev)+yy(jnext))/2;
end
% radius of the arches
rc1=norm([xx(1) yy(1)]-[xx(2) yy(2)]);
% plot of the intersecting arches 
j=1;
for i=1:n
    thetac=linspace(theta1(j)-pi/2, theta1(j)+pi/2);
    sc=xxc(i)+rc1*cos(thetac);
    tc=yyc(i)+rc1*sin(thetac);
    plot(sc,tc,'Color',stringa,'LineWidth',3,'LineJoin', 'chamfer')
    j=j+2;
end
axis square
end
