function  rc1=npetals(n,r0,r,stringa)
%function  rc1=npetals(n,r0,r,stringa)
% inputs
%        n -  The number of columns  with their arches.
%        r0 - The starting radius of the columns.
%        r  - The ending radius of the columns.
%        stringa - The color of the lines and curves generated by the function.
% output
%        rc1 - The radius of the arches.
%
% MIT license 
% Copyright (c) Annamaria Mazzia
%
theta1=linspace(pi/2,pi/2+2*pi,n+1);
% construction of the columns
xx0=r0*cos(theta1(1:n)); yy0=r0*sin(theta1(1:n)); % segment base vertices
xx=r*cos(theta1(1:n)); yy=r*sin(theta1(1:n));  % segment end vertices
%
% construction of the  arches' centroids
xxc=(xx(1:end-1)+xx(2:end))/2; yyc=(yy(1:end-1)+yy(2:end))/2;
xxc=[xxc  (xx(end)+xx(1))/2]; yyc=[yyc  (yy(end)+yy(1))/2];
%
% plot of the columns
for i=1:n
   plot([xx0(i) xx(i)],[yy0(i) yy(i)],'Color',stringa,'LineWidth',2, 'LineJoin', 'chamfer')
end
%  radius of the arches
rc1=norm([xx(1) yy(1)]-[xxc(1) yyc(1)]);
% plot of the arches 
for i=1:n
    t1=theta1(i)+pi/n; 
    thetac=linspace(t1-pi/2, t1+pi/2); 
    % sc and tc are the x- and y-coordinates of the arches 
    sc=xxc(i)+rc1*cos(thetac);
    tc=yyc(i)+rc1*sin(thetac);
    plot(sc,tc,'Color',stringa,'LineWidth',2,'LineJoin', 'chamfer')
end
