function    plot_tricircle(n,xxc,yyc, rrr,stringa)
% function    plot_tricircle(n,xxc,yyc, rrr,stringa)
% inputs
%        n -  The number of columns  with their arches.
%        xcc - x-coordinates of the centroids of the three-circle curve 
%        ycc - y-coordinates of the centroids of the three-circle curve
%        rrr - radius of the circle.
%        stringa - The color of the lines and curves generated by the function.
% output
%      This function has no output variable; it just generates the plot.
%
% MIT license 
% Copyright (c) Annamaria Mazzia
%
% Load coordinates for the three-circle curve. The points are generated by
% the script_trefoilmotif.m script
A=load('filetricircle.dat');
xu=A(1,:);
yu=A(2,:);
theta1=linspace(pi/2,pi/2+2*pi,n+1);
rot=@(t1) [cos(t1) -sin(t1); sin(t1) cos(t1)]; % rotation matrix function
for j=1:n
 dxx=rrr*xu; dyy=rrr*yu; %dilation
for i=1:length(xu)
    y=rot(theta1(j)-pi/2)*[dxx(i); dyy(i)]; %rotation
    dxx(i)=y(1)+xxc(j);  %translation
    dyy(i)=y(2)+yyc(j);
end
plot(dxx,dyy,'Color',stringa,'LineWidth',2,'LineJoin', 'chamfer')

end
