function  [xu,yu]=trilobi(n,r,r0,rc1,stringa)
% function  trilobi(n,m,r,r0,rc1,stringa)
% inputs
%      n -  number of times in which the parametric curve will be replicated
%           along the band
%      r -  outer radius of the circular band
%      r0 - inner radius of the circular band
%      rc1 - radius of the arches.
%      stringa - The color of the lines and curves generated by the function.
% output
%      xu  - x-coordinates of the half trefoil motif
%      yu  - y-coordinates of the half trefoil motif
% MIT license 
% Copyright (c) Annamaria Mazzia
%
% Load coordinates for the half trefoil motif. The points are generated by
% the script_halftrefoilmotif.m script
A=load('filesemitricircle.dat');
xu=A(1,:);
yu=A(2,:);
rot=@(t1) [cos(t1) -sin(t1); sin(t1) cos(t1)]; % rotation matrix function
%%%%%%%%%%%%%%%%%%%%%%%%%
m=2*n;
theta1=linspace(pi/2,pi/2+2*pi,m+1);
xx=r*cos(theta1(2:2:m+1)); yy=r*sin(theta1(2:2:m+1));% The coordinates 
% of the centroid points that are the centers from which the half 
% trefoil motif starts.
xx0=r0*cos(theta1(2:2:m)-pi/n); yy0=r0*sin(theta1(2:2:m)-pi/n); % Points at 
% the base of the band for drawing the right inclined column starting from 
% the trefoil motif.
xx00=r0*cos(theta1(2:2:m)+pi/n); yy00=r0*sin(theta1(2:2:m)+pi/n); % Points at 
% the base of the band for drawing the left inclined column starting from 
% the trefoil motif.
%
% plot of the half trefoil motif with inclined columns starting from 
% its extreme points
jjj=2;
for i=1:n
  dxx=0.8*rc1*xu; dyy=0.8*rc1*yu; %dilation 
        for ii=1:length(xu)
            yr=rot(theta1(jjj)-pi/2)*[dxx(ii); dyy(ii)]; %rotation
            dxx(ii)=yr(1)+xx(i); %translation
            dyy(ii)=yr(2)+yy(i);
        end
        jjj=jjj+2;
        plot(dxx,dyy,'Color',stringa,'LineWidth',2,'LineJoin', 'chamfer')
        plot([xx0(i)  dxx(1)],[yy0(i) dyy(1)],'Color',stringa,'LineWidth',2,'LineJoin', 'chamfer')
        plot([xx00(i)  dxx(end)],[yy00(i) dyy(end)],'Color',stringa,'LineWidth',2,'LineJoin', 'chamfer')
end
end
